libtracefs: Fix mistaken update to TRACEFS_STACKTRACE macro
The change that converted generic names to variables to start with "tfs_"
was a bit too aggressive and ended up changing the string name of
"common_stacktrace" which broke trace_sql():

When running sqlhist, it would get the following error:

  # ./bin/sqlhist -n wake_lat 'select start.pid, start.common_stacktrace, TIMESTAMP_DELTA_USECS as delta from sched_waking as start join sched_switch as end on start.pid = end.next_pid'
  Failed creating synthetic event!: Success
  select start.pid, start.common_stacktrace, TIMESTAMP_DELTA_USECS as delta from sched_waking as start join sched_switch as end on start.pid = end.next_pid
                    ^
  ERROR: 'start.common_stacktrace'
  Field 'common_stacktrace' not part of event sched_waking

When it should have produced:

  # ./bin/sqlhist -n wake_lat 'select start.pid, start.common_stacktrace, TIMESTAMP_DELTA_USECS as delta from sched_waking as start join sched_switch as end on start.pid = end.next_pid'
  echo 's:wake_lat pid_t pid; unsigned long common_stacktrace[]; u64 delta;' >> /sys/kernel/tracing/dynamic_events
  echo 'hist:keys=pid:__arg_15169_2=pid,__arg_15169_4=common_stacktrace,__arg_15169_5=common_timestamp.usecs' >> /sys/kernel/tracing/events/sched/sched_waking/trigger
  echo 'hist:keys=next_pid:__pid_15169_1=$__arg_15169_2,__common_stacktrace_15169_3=$__arg_15169_4,__delta_15169_6=common_timestamp.usecs-$__arg_15169_5:onmatch(sched.sched_waking).trace(wake_lat,$__pid_15169_1,$__common_stacktrace_15169_3,$__delta_15169_6)' >> /sys/kernel/tracing/events/sched/sched_switch/trigger

Cc: Metin Kaya <metin.kaya@arm.com>
Link: https://lore.kernel.org/20250407172013.6aa58191@gandalf.local.home
Fixes: a2bfb49f ("libtracefs: utest: Rename private functions to fix static building")
Signed-off-by: Steven Rostedt (Google) <rostedt@goodmis.org>