libtracefs: Make comm field a string
The COMM or comm that is used in filtering and creating synthetic events is
a string, but it isn't defined as such when it is created. This limits how
creating synthetic events with COMM can work.

Without designating COMM as a string, the following:

  sqlhist -n hello select start.COMM from sched_switch as start where start.COMM = '"hello"'

Errors out with:

  Failed creating synthetic event!: Invalid argument
  select start.COMM from sched_switch as start where start.COMM = "hello"
         ^
  ERROR: 'start.COMM'
  Field 'COMM' is not compatible to be compared with the given value

Link: https://lore.kernel.org/20250827184003.17c63731@gandalf.local.home
Signed-off-by: Steven Rostedt (Google) <rostedt@goodmis.org>