libtracefs: Fix libtracefs-instance-affinity.txt document
The building of the Documentation directory errors with:

  DESCEND            Documentation all
  ASCIIDOC libtracefs-instances-affinity.html
asciidoc: ERROR: libtracefs-instances-affinity.txt: line 8: malformed name section body
asciidoc: FAILED: libtracefs-instances-affinity.txt: line 8: unexpected error:
asciidoc: ------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/asciidoc/asciidoc.py", line 6081, in asciidoc
    document.translate(has_header)  # Generate the output.
  File "/usr/lib/python3/dist-packages/asciidoc/asciidoc.py", line 1380, in translate
    self.attributes['manname'] = mo.group('manname').strip()
AttributeError: 'NoneType' object has no attribute 'group'
make[1]: *** [Makefile:237: libtracefs-instances-affinity.html] Error 1
make: *** [Makefile:286: doc] Error 2

This was due to a cut and paste error and the first line did not have a
hyphen for the description of the man page.

Link: https://lore.kernel.org/linux-trace-devel/20220119111901.0a18aa2c@gandalf.local.home

Signed-off-by: Steven Rostedt (Google) <rostedt@goodmis.org>
Reviewed-by: Krzysztof Kozlowski <krzysztof.kozlowski@canonical.com>
Signed-off-by: Steven Rostedt (Google) <rostedt@goodmis.org>