libtracefs: Fix compiling with musl
The library does not build with musl due to a missing pthread.h include.

Fixes errors in the form of:

  In file included from tracefs-utils.c:21:
  ...cortex-a53_musl/libtracefs-1.4.1/include/tracefs-local.h:30:9:
    error: unknown type name 'pthread_mutex_t'
     30 |         pthread_mutex_t                 lock;
        |         ^~~~~~~~~~~~~~~
  .../cortex-a53_musl/libtracefs-1.4.1/include/tracefs-local.h:41:8:
    error: unknown type name 'pthread_mutex_t'
     41 | extern pthread_mutex_t toplevel_lock;
        |        ^~~~~~~~~~~~~~~
  ...cortex-a53_musl/libtracefs-1.4.1/include/tracefs-local.h:43:15:
    error: unknown type name 'pthread_mutex_t'
     43 | static inline pthread_mutex_t *trace_get_lock(struct ...
        |               ^~~~~~~~~~~~~~~

Link: https://lore.kernel.org/linux-trace-devel/20220711141459.2972e95b@gandalf.local.home

Signed-off-by: Nick Hainke <vincent@systemli.org>
Signed-off-by: Steven Rostedt (Google) <rostedt@goodmis.org>